language: python

python:
    - "3.3"
    - "3.4"

services:
    - redis-server

before_install:
    - sh bin/check_signoff.sh

install:
    - pip install -q coveralls flake8
    - pip install -q -e .
    - pip install -r tests/requirements.txt

before_script:
    - flake8
    - sh tests/start-neo4j.sh
    - origins serve --debug &

script:
    - coverage run test_suite.py

after_success:
    - coveralls > /dev/null
